# ref: https://github.com/rxhanson/Rectangle/blob/master/.github/workflows/build.yml

name: Build

on: [push, pull_request]

permissions: read-all

env:
  XCODE_SCHEME: "EjectKey"
  BUILD_DIR: "build"
  XCODE_ARCHIVE: "EjectKey.xcarchive"
  EXPORT_OPTIONS_PLIST: "exportOptions.plist"
  CODE_SIGN_IDENTITY: "-"
  APP_NAME: "EjectKey.app"
  DMG_NAME: "EjectKey"
  DMG_FILE_NAME: "EjectKey.dmg"

jobs:
  test:
    runs-on: macOS-latest
    env:
      MINT_PATH: mint/lib
      MINT_LINK_PATH: mint/bin
    steps:
    - name: Show Xcode version
      run: xcodebuild -version    
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install Mint
      run: brew install mint
    - name: Cache Mint packages
      uses: actions/cache@v2
      with:
        path: mint
        key: ${{ runner.os }}-mint-${{ hashFiles('**/Mintfile') }}
        restore-keys: |
          ${{ runner.os }}-mint-
    - name: Build
      run: xcodebuild -scheme "$XCODE_SCHEME" archive -archivePath "$BUILD_DIR/$XCODE_ARCHIVE"
    - name: Export
      run: |
        plutil -convert xml1 - -o "$EXPORT_OPTIONS_PLIST" << EOF
          {
            "destination": "export",
            "method": "mac-application"
          }
        EOF
        xcodebuild -exportArchive -archivePath "$BUILD_DIR/$XCODE_ARCHIVE" -exportPath "$BUILD_DIR" -exportOptionsPlist "$EXPORT_OPTIONS_PLIST"
    - name: Resign App
      run: codesign --force --deep -s "$CODE_SIGN_IDENTITY" "$BUILD_DIR/$APP_NAME"
    - name: Make DMG
      run: hdiutil create -srcdir "$BUILD_DIR" -volname "$DMG_NAME" "$DMG_FILE_NAME"
    - name: Upload
      uses: actions/upload-artifact@v3
      with:
        name: Build
        path: ${{ env.DMG_FILE_NAME }}


