# ref: https://github.com/RobotsAndPencils/XcodesApp/blob/main/.github/workflows/appcast.yml

name: Build and publish a website

on:
  workflow_dispatch:
  release:
  push:
    branches:
      - website
    paths-ignore:
      - README.md

jobs:
  jekyll:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout 🛎
      uses: actions/checkout@v3
      with:
        # If you're using actions/checkout@v3 you must set persist-credentials to false in most cases for the deployment to work correctly.
        persist-credentials: false
        ref: website

    - name: Cache 📦
      uses: actions/cache@v3.2.2
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-v1.0-${{ hashFiles('Gemfile') }}
        restore-keys: |
          ${{ runner.os }}-gems-
          
    - name: Ruby ♦️
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.7'

    - name: Bundler 💎
      env:
        BUNDLE_PATH: vendor/bundle
      run: |
        gem install bundler
        bundle install

    - name: Build 🛠
      env:
        BUNDLE_PATH: vendor/bundle
        JEKYLL_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: bundle exec jekyll build
      
    - name: Publish 🚀
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: _site